"""SMPL-X model constants: joint count, joint names, landmark vertex IDs."""

from typing import List, Literal


Gender = Literal["neutral", "male", "female"]

SMPLX_NUM_VERTICES: int = 10475
SMPLX_NUM_JOINTS: int = 55
SMPLX_NUM_POSE_DIRS: int = 486  # (SMPLX_NUM_JOINTS - 1) * 9
SMPLX_NUM_SHAPE_COEFFS: int = 300

# skeletal joints in SMPL-X kinematic-tree order
SMPLX_JOINT_NAMES: List[str] = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "jaw",
    "left_eye_smplhf",
    "right_eye_smplhf",
    "left_index1",
    "left_index2",
    "left_index3",
    "left_middle1",
    "left_middle2",
    "left_middle3",
    "left_pinky1",
    "left_pinky2",
    "left_pinky3",
    "left_ring1",
    "left_ring2",
    "left_ring3",
    "left_thumb1",
    "left_thumb2",
    "left_thumb3",
    "right_index1",
    "right_index2",
    "right_index3",
    "right_middle1",
    "right_middle2",
    "right_middle3",
    "right_pinky1",
    "right_pinky2",
    "right_pinky3",
    "right_ring1",
    "right_ring2",
    "right_ring3",
    "right_thumb1",
    "right_thumb2",
    "right_thumb3",
]

# 21 static landmarks: face(5) + feet(6) + hand fingertips(10), in the order
# the upstream MPI `VertexJointSelector` appends them.
SMPLX_STATIC_LANDMARK_NAMES: List[str] = [
    "nose",
    "right_eye",
    "left_eye",
    "right_ear",
    "left_ear",
    "left_big_toe",
    "left_small_toe",
    "left_heel",
    "right_big_toe",
    "right_small_toe",
    "right_heel",
    "left_thumb",
    "left_index",
    "left_middle",
    "left_ring",
    "left_pinky",
    "right_thumb",
    "right_index",
    "right_middle",
    "right_ring",
    "right_pinky",
]
SMPLX_STATIC_LANDMARK_VERTEX_IDS: List[int] = [
    9120,
    9929,
    9448,
    616,
    6,
    5770,
    5780,
    8846,
    8463,
    8474,
    8635,
    5361,
    4933,
    5058,
    5169,
    5286,
    8079,
    7669,
    7794,
    7905,
    8022,
]
